{
    "e": "not_empty",
    "cc": "<style>.flags .flag{display:inline-block;height:32px;width:32px;vertical-align:text-top;line-height:32px;background:url(https:\/\/timmapwormate.com\/images\/check\/flags.png) no-repeat;} .flags .br{background-position:0px 0px;} .flags .us{background-position:0px -35px;} .flags .ca{background-position:0px -71px;} .flags .mx{background-position:0px -106px;} .flags .de{background-position:0px -141px;} .flags .fr{background-position:0px -177px;} .flags .sg{background-position:0px -212px;} .flags .jp{background-position:0px -247px;} .flags .au{background-position:0px -283px;} .flags .gb{background-position:0px -318px;}<\/style><img src=\"https:\/\/i.imgur.com\/qBk8hcZ.png\" style=\"height: 42px; background-image: linear-gradient(#a9938c, #000000); font-weight: bold; color: white; border-radius: 5px; border: 1px solid black; position: absolute; z-index: 1;}\" title=\"T\u00ecm map wormate\"><div id=\"div_map\"><table class=\"flags\"><tr><td class=\"center\"><a id=\"flag_de\" class=\"area_show\"><span class=\"flag de\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_fr\"><span class=\"flag fr\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_sg\"><span class=\"flag sg\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_ca\"><span class=\"flag ca\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_mx\"><span class=\"flag mx\"><\/span><\/a><\/td><\/tr><tr><td class=\"center\"><a id=\"flag_br\"><span class=\"flag br\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_us\"><span class=\"flag us\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_jp\"><span class=\"flag jp\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_au\"><span class=\"flag au\"><\/span><\/a><\/td><td class=\"center\"><a id=\"flag_gb\"><span class=\"flag gb\"><\/span><\/a><\/td><\/tr><\/table><hr style=\"margin: 0;\"><div id=\"area_br\" class=\"area_map div_hidden\"><p style=\"text-align: center;font-size: 20px;\">Updating.<br>Please wait, Thanks.<\/p><\/div><div id=\"area_us\" class=\"area_map div_hidden\"><\/div><div id=\"area_ca\" class=\"area_map div_hidden\"><\/div><div id=\"area_mx\" class=\"area_map div_hidden\"><p style=\"text-align: center;font-size: 20px;\">Updating.<br>Please wait, Thanks.<\/p><\/div><div id=\"area_de\" class=\"area_map div_show\">\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_1\" data-port=\"wss:\/\/fra-c.wormate.io:32053\/wormy\">01. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@test\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/test1.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_2\" data-port=\"wss:\/\/fra-c.wormate.io:32609\/wormy\">02.Germany 2<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.tiktok.com\/@test2.io1\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/test2.jpeg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_3\" data-port=\"wss:\/\/fra-c.wormate.io:32103\/wormy\">03. &nbsp;03. Germany<\/a><a href=\"https:\/\/www.facebook.com\/TeamNike2\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/nike.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_4\" data-port=\"wss:\/\/fra-c.wormate.io:32064\/wormy\">04. Germany<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.tiktok.com\/@maro_kng\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/mano_png.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_5\" data-port=\"wss:\/\/fra-c.wormate.io:32708\/wormy\">05.Germany<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/marshmelo.gamer\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/melo.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_6\" data-port=\"wss:\/\/fra-c.wormate.io:32026\/wormy\">06.Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@lb.salim1\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/salim.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_7\" data-port=\"wss:\/\/fra-c.wormate.io:32285\/wormy\">07. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@pindi__gaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/fire.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_8\" data-port=\"wss:\/\/fra-c.wormate.io:31280\/wormy\">08. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@karim_g11\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/karim.png\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_9\" data-port=\"wss:\/\/fra-c.wormate.io:32017\/wormy\">09. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@tik.na4\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/NS.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_10\" data-port=\"wss:\/\/fra-c.wormate.io:32095\/wormy\">10. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@dzirigaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/dziri.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_11\" data-port=\"wss:\/\/fra-c.wormate.io:31050\/wormy\">11. Germany<\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_12\" data-port=\"wss:\/\/fra-c.wormate.io:30956\/wormy\">12. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@xxshadi1\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/shadi.png\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_13\" data-port=\"wss:\/\/fra-c.wormate.io:32567\/wormy\">13. Germany<\/a><a href=\"https:\/\/www.tiktok.com\/@aoto_gaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/aoto.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_14\" data-port=\"wss:\/\/fra-c.wormate.io:31886\/wormy\">14. Germany<\/a><a href=\"https:\/\/discord.gg\/rps2AUcp\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/DZ.png\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_15\" data-port=\"wss:\/\/fra-c.wormate.io:31403\/wormy\">15. Germany<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100083316140496\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/sherwani.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_16\" data-port=\"wss:\/\/fra-c.wormate.io:30501\/wormy\">16. &nbsp;\u0623\u0644\u0645\u0627\u0646\u064a\u0627<\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_17\" data-port=\"wss:\/\/fra-c.wormate.io:32196\/wormy\">17. &nbsp;tik \ud80c\udf39 \ud835\udce1 \ud835\udcde \ud835\udcde \ud835\udce3 \u2717 sy<\/a><a href=\"https:\/\/www.tiktok.com\/@root.sy\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/root_sy.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_18\" data-port=\"wss:\/\/fra-c.wormate.io:32625\/wormy\">18. &nbsp;Saeedi Gaming<\/a><a href=\"https:\/\/www.facebook.com\/SaeediGaming86\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/saeedi.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_19\" data-port=\"wss:\/\/fra-c.wormate.io:30201\/wormy\">19. &nbsp;Glitch Berlin<\/a><a href=\"https:\/\/www.tiktok.com\/@berlin52.hz\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/52hz.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"DE_20\" data-port=\"wss:\/\/fra-c.wormate.io:30988\/wormy\">20. &nbsp;\u0623\u0644\u0645\u0627\u0646\u064a\u0627<\/a><\/div><\/div><div id=\"area_fr\" class=\"area_map div_hidden\">\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_1\" data-port=\"wss:\/\/fra-c.wormate.io:32053\/wormy\">01. &nbsp;D V BLACK<\/a><a href=\"https:\/\/www.tiktok.com\/@sallh.sy\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/dv_black.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_2\" data-port=\"wss:\/\/fra-c.wormate.io:32609\/wormy\">02. &nbsp;\u0641\u0631\u0646\u0633\u0627<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_3\" data-port=\"wss:\/\/fra-c.wormate.io:32103\/wormy\">03. &nbsp;KENT AV\u0130ZE<\/a><a href=\"https:\/\/www.tiktok.com\/@kentavize?lang=tr-TR\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/KA.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_4\" data-port=\"wss:\/\/fra-c.wormate.io:32064\/wormy\">04. &nbsp;E\u011eLENCE D\u00dcNYAM<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.tiktok.com\/@tc.hilmitekmen?lang=tr-TR\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/eg.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_5\" data-port=\"wss:\/\/fra-c.wormate.io:32708\/wormy\">05. &nbsp;SivasL\u0131 Gaminq<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.tiktok.com\/@sivasli_gaming?lang=tr-TR\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/SG.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_6\" data-port=\"wss:\/\/fra-c.wormate.io:32026\/wormy\">06. &nbsp;Alfa Casper org Gaming<\/a><a href=\"https:\/\/www.tiktok.com\/@alfaorg\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/alfaorg.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_7\" data-port=\"wss:\/\/fra-c.wormate.io:32285\/wormy\">07. &nbsp;DV DAVINCI<\/a><a href=\"https:\/\/www.tiktok.com\/@dv.davinci\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/davinci.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_8\" data-port=\"wss:\/\/fra-c.wormate.io:31280\/wormy\">08. &nbsp;\u2730\ud835\udc05\ud835\udc68\u13de\u13de\ud835\udc14\u13ab\ud835\udc68\u13bb\u2730<\/a><a href=\"https:\/\/www.tiktok.com\/@_fallujah_\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/fallujah.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_9\" data-port=\"wss:\/\/fra-c.wormate.io:32017\/wormy\">09. &nbsp;Glitch Gaming<\/a><a href=\"https:\/\/www.facebook.com\/glitchgamingvas\/\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/glitch.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_10\" data-port=\"wss:\/\/fra-c.wormate.io:32095\/wormy\">10. &nbsp;\u2620\ud835\udc72\ud835\udc68\ud835\udc69\ud835\udc7b\ud835\udc7a\ud835\udc6f\ud835\udc70\ud835\udc75\ud835\udc76\u2620<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100087458370473\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/kabtshino.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_11\" data-port=\"wss:\/\/fra-c.wormate.io:31050\/wormy\">11. &nbsp;tik\/Malek Gaming<\/a><a href=\"https:\/\/www.tiktok.com\/@g1sc\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/g1sc.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_12\" data-port=\"wss:\/\/fra-c.wormate.io:30956\/wormy\">12. &nbsp;Kamikaze Gaming<\/a><a href=\"https:\/\/www.tiktok.com\/@kamikazegaming34\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/Kami.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_13\" data-port=\"wss:\/\/fra-c.wormate.io:32567\/wormy\">13. &nbsp;\u300e \ud80c\udda9 \u02f9\ud835\ude82\ud835\ude7e\ud835\ude7b\ud835\ude7e\u1d31\u1d33\u02fc\u00a0\ud80c\uddaa\u300f<\/a><a href=\"https:\/\/www.tiktok.com\/@5rur\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/5rur.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"FR_14\" data-port=\"wss:\/\/fra-c.wormate.io:31886\/wormy\">14. &nbsp;SM3AN GAMING<\/a><a href=\"https:\/\/www.tiktok.com\/@sm3angaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/sm3an.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div><\/div><div id=\"area_sg\" class=\"area_map div_hidden\"><p id=\"pusg_1\" style=\"text-align: center;font-size: 20px;\">Please clear your browsing history to update the list of Singapore maps<\/p><div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_1\" data-port=\"wss:\/\/fra-c.wormate.io:32053\/wormy\">01. &nbsp;\u2744\ufe0f SCD \ud835\udd6e\ud835\udd8e\ud835\udd93\ud835\udd89\ud835\udd9e\ud835\udd93\ud835\udd86\ud835\udd93\ud835\udd86<\/a><a href=\"https:\/\/www.tiktok.com\/@tong.cindy\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/cindynana.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_2\" data-port=\"wss:\/\/fra-c.wormate.io:32609\/wormy\">02. &nbsp;\u2744\ufe0f SCD Mu\u1ed9i Mu\u1ed9i<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100092254689927\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/hoangduy.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_3\" data-port=\"wss:\/\/fra-c.wormate.io:32103\/wormy\">03. &nbsp;GLITCH \ud83d\ude48 NOURA<\/a><a href=\"https:\/\/www.tiktok.com\/@glitchnoura\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/glithchnoura.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_4\" data-port=\"wss:\/\/fra-c.wormate.io:32064\/wormy\">04. &nbsp;\ud83c\udf52Cherry Land<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/Cherry9123\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/cherry.png\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_5\" data-port=\"wss:\/\/fra-c.wormate.io:32708\/wormy\">05. &nbsp;\ud83d\udc8e\ud83e\ude93\ud83c\udd7a\ud83c\udd77\ud835\udc3f\ud835\udc52\ud835\udcb6\ud835\udcc3\ud835\udc54 168<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/KHLeangGaming168\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/KHLeng.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_6\" data-port=\"wss:\/\/fra-c.wormate.io:32026\/wormy\">06. &nbsp;VQH.Gaming<\/a><a href=\"https:\/\/www.tiktok.com\/@vqh.48\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/vqh.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_7\" data-port=\"wss:\/\/fra-c.wormate.io:32285\/wormy\">07. &nbsp;\u1d40\u1d9c\u1d40\u2c7d Tu\u1ea5n C\u1ea3nh TV<\/a><a href=\"https:\/\/www.facebook.com\/tuancanhTCTV\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/tuancanh.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_8\" data-port=\"wss:\/\/fra-c.wormate.io:31280\/wormy\">08. &nbsp;\ud83d\udd25\ud83d\udc09 61c.39239<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100076038386454\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/61c.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_9\" data-port=\"wss:\/\/fra-c.wormate.io:32017\/wormy\">09. &nbsp;\u1d2c\u1d31\ud83c\udd83\ud83c\udd85\ud83c\udd83\ud83c\udfa4C\u1eadu c\u00f2i TV<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100064318623308\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/cau_coi.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_10\" data-port=\"wss:\/\/fra-c.wormate.io:32095\/wormy\">10. &nbsp;\u2744\ufe0fSCD.\ud835\udc6f\ud835\udc82\u0323\u0302\ud835\udc96 \ud835\udc72\ud835\udc96\ud835\udc8f\ud835\udc9b<\/a><a href=\"https:\/\/www.tiktok.com\/@haukunz76\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/haukun.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_11\" data-port=\"wss:\/\/fra-c.wormate.io:31050\/wormy\">11. &nbsp;\ud83d\udc3b ADH Di\u00eam V\u01b0\u01a1ng<\/a><a href=\"https:\/\/www.facebook.com\/vuongvanle1986\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/diemvuong.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_12\" data-port=\"wss:\/\/fra-c.wormate.io:30956\/wormy\">12. &nbsp;X\u00e0 Tinh Gaming<\/a><a href=\"https:\/\/www.facebook.com\/thuan151084\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/xatinh.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_13\" data-port=\"wss:\/\/fra-c.wormate.io:32567\/wormy\">13. &nbsp; \ud83d\udcb0\ud83c\udd85\ud83c\udd76\ud83d\udcb8 VI\u1ec6T KI\u00caN\ud83c\udf39<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100063915230765\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/vietkien.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_14\" data-port=\"wss:\/\/fra-c.wormate.io:31886\/wormy\">14. &nbsp;\ud83c\udf81KHUN ACE\ud83c\udf81<\/a><a href=\"https:\/\/www.facebook.com\/khunace168\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/KhunAce.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_15\" data-port=\"wss:\/\/fra-c.wormate.io:31403\/wormy\">15. &nbsp;\ud83c\udf08\ud83c\udd82\ud83c\udd77\u2764\ufe0f Sam V\u1ecbt<\/a><a href=\"https:\/\/www.facebook.com\/Samtutinhhoa\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/sam.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_16\" data-port=\"wss:\/\/fra-c.wormate.io:30501\/wormy\">16. &nbsp;\ud83c\udf53Cu Tr\u01b0\u1eddng Gaming\ud83c\udf38<\/a><a href=\"https:\/\/www.tiktok.com\/@wormate.iolive\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/CutruongGM.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_17\" data-port=\"wss:\/\/fra-c.wormate.io:32196\/wormy\">17. &nbsp;\ud83d\udd25\ud83d\udc09 Ng\u00e0 \u0103n t\u1ecfi GM<\/a><a href=\"https:\/\/www.facebook.com\/Ngangao000\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/nga_toi.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_18\" data-port=\"wss:\/\/fra-c.wormate.io:32625\/wormy\">18. &nbsp;\ud83d\udca3Tr\u01b0\u1eddng Bom TV<\/a><a href=\"https:\/\/www.facebook.com\/truongbomgaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/truongboom.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_19\" data-port=\"wss:\/\/fra-c.wormate.io:30201\/wormy\">19. &nbsp;\u1d2d\ud83e\udd9c\u2102\ud835\udd59\ud835\udd5a\ud835\udd5e\ud835\udd4a\u01a1\ud835\udd5f\u2102\ud835\udd52\ud83c\udff9<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100086944465949\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/votu.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_20\" data-port=\"wss:\/\/fra-c.wormate.io:30988\/wormy\">20. &nbsp;\ud83c\udf51 Chung Ru\u1ed3i Gaming<\/a><a href=\"https:\/\/www.facebook.com\/Cr.chungruoigaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/chungruoigaming.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_21\" data-port=\"wss:\/\/fra-c.wormate.io:32249\/wormy\">21. &nbsp;FB: Girl ADH<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100075939892854\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/girl_adh.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_22\" data-port=\"wss:\/\/fra-c.wormate.io:32262\/wormy\">22. &nbsp;\ud83e\udd55 Akira Gaming<\/a><a href=\"https:\/\/www.facebook.com\/profile.php?id=100077450623669\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/akira.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_23\" data-port=\"wss:\/\/fra-c.wormate.io:32103wormy\">23. &nbsp; Ti\u1ec3u Th\u01b0 K\u00fd Gaming<\/a><a href=\"https:\/\/www.facebook.com\/tieuthukygaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/tieuthuky.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_24\" data-port=\"wss:\/\/fra-c.wormate.io:32064\/wormy\">24. &nbsp;FB\ud83d\udc30Ho\u00e0ngH\u00f4nTV<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/hoanghontv\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/hoanghon.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_25\" data-port=\"wss:\/\/fra-c.wormate.io:32708\/wormy\">25. &nbsp;\u26c4SQ\ud83c\udf3aSalju Qaseh\ud83d\udc30<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.facebook.com\/SQSaljuQaseh\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/sq.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_26\" data-port=\"wss:\/\/fra-c.wormate.io:32026\/wormy\">26. &nbsp;\ud83c\udf44\ud83c\udd7c\ud83c\udd72M\u1ea1nh C\u00f2i TV<\/a><a href=\"https:\/\/www.tiktok.com\/@hoaxuanmanh93\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/manhcoi_gm.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_27\" data-port=\"wss:\/\/fra-c.wormate.io:32285\/wormy\">27. &nbsp;C\u1eacUBIN \ud83d\udc18\u2764\ufe0f\u2764\ufe0f\u2764\ufe0f<\/a><a href=\"https:\/\/www.tiktok.com\/@caubinranio\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/caubin.jpeg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_28\" data-port=\"wss:\/\/fra-c.wormate.io:31280\/wormy\">28. &nbsp;L\u1ed9c S\u1eb9o TV<\/a><a href=\"https:\/\/www.tiktok.com\/@locseotv\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/locseo.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_29\" data-port=\"wss:\/\/fra-c.wormate.io:32017\/wormy\">29. &nbsp;C\u00f4 Ch\u1ee7 Nh\u1ecf\ud83d\udda4<\/a><a href=\"https:\/\/www.tiktok.com\/@uyen_baby1\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/cochunho.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_30\" data-port=\"wss:\/\/fra-c.wormate.io:32095\/wormy\">30. &nbsp;CG \ud83d\udc9a Li\u00ean T\u1ee7n \ud83d\udc9a<\/a><a href=\"https:\/\/www.facebook.com\/cglientun\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/Lientun.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_31\" data-port=\"wss:\/\/sin-b.wormate.io:31050\/wormy\">31. &nbsp;\ud83c\udf38\u1d40\u1d35\u1d37\u1d40\u1d3c\u1d37 S\ud835\udc04N \u0110\ud835\udc00\u0301 \u1d33\u1d39<\/a><a href=\"https:\/\/www.tiktok.com\/@senda_gaming\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/senda.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_32\" data-port=\"wss:\/\/sin-b.wormate.io:30956\/wormy\">32. &nbsp;\ud83e\udd8b\u2076\u2078\u2076\u2078 Cu L\u1ebfch TV<\/a><a href=\"https:\/\/www.tiktok.com\/@culech247\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/culech.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_33\" data-port=\"wss:\/\/sin-b.wormate.io:32567\/wormy\">33. &nbsp;H\u00e0 H\u00e0 Xuka<\/a><a href=\"https:\/\/www.tiktok.com\/@haha.3009\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/hahaxuka1994.png\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_34\" data-port=\"wss:\/\/sin-b.wormate.io:31886\/wormy\">34. &nbsp;\ud83d\udc33\ud835\udc0b\ud835\udc28\ud835\udc27\ud835\udc20 \ud835\udc07\u1ea3\ud835\udc22\ud83c\udf0a<\/a><a href=\"https:\/\/www.tiktok.com\/@longhai1188\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/Longhai.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_35\" data-port=\"wss:\/\/fra-c.wormate.io:31403\/wormy\">35. &nbsp;\ud83d\udd25\u0110\u00f4\ud835\udc0b\ud835\udc1a\u2763\ufe0f<\/a><a href=\"https:\/\/www.tiktok.com\/@dola.gamer\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/duc_dola.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_36\" data-port=\"wss:\/\/fra-c.wormate.io:30501\/wormy\">36. &nbsp;\ud83d\udc33\ud835\udc12\ud835\udc1a\ud835\udc27\ud835\udc20 \ud835\udc12\ud835\udc2e\ud835\udc27\ud83c\udf0a<\/a><a href=\"https:\/\/www.tiktok.com\/@sangsunn98\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/Sangsun.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"SG_37\" data-port=\"wss:\/\/sin-b.wormate.io:32196\/wormy\">37. &nbsp;Endha Agustin<\/a><a href=\"https:\/\/www.facebook.com\/Endha.Agustin\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/ea.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div><\/div><div id=\"area_jp\" class=\"area_map div_hidden\"><p style=\"text-align: center;font-size: 20px;\">Updating.<br>Please wait, Thanks.<\/p><\/div><div id=\"area_au\" class=\"area_map div_hidden\"><div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"AU_1\" data-port=\"wss:\/\/fra-c.wormate.io:32053\/wormy\">01. &nbsp;SRTIRAQTIK<\/a><a href=\"https:\/\/www.tiktok.com\/@srtiraqq\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/srtiraqq.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"AU_2\" data-port=\"wss:\/\/fra-c.wormate.io:32609\/wormy\">02. &nbsp;Paman Rizky<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><a href=\"https:\/\/www.tiktok.com\/@pamanrizky\" target=\"_blank\" style=\"position: absolute;right: 0px;top: -2px;\"><img src=\"https:\/\/timmapwormate.com\/images\/check\/paman_rizky.jpg\" style=\"width: 25px; vertical-align: middle\"><\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"AU_3\" data-port=\"wss:\/\/fra-c.wormate.io:32103\/wormy\">03. &nbsp;\u0623\u0633\u062a\u0631\u0627\u0644\u064a\u0627<\/a><\/div>\r\n\t\t\t\t\t\t<div class=\"div_item\"><a href=\"\" class=\"select_item\" data-name=\"AU_4\" data-port=\"wss:\/\/fra-c.wormate.io:32064\/wormy\">04. &nbsp;\u0623\u0633\u062a\u0631\u0627\u0644\u064a\u0627<span style=\"background-color: #4dff00;width: 12px;height: 12px;border-radius: 12px;margin-top: 9px;margin-right: 28px;float: right;\"><\/span><\/a><\/div><\/div><div id=\"area_gb\" class=\"area_map div_hidden\"><p style=\"text-align: center;font-size: 20px;\">Updating.<br>Please wait, Thanks.<\/p><\/div><\/div><script> $(\"#flag_br\").click(function(){ $(\"#flag_br\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_br\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_fr,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_us\").click(function(){ $(\"#flag_us\").addClass(\"area_show\"); $(\"#flag_br,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_us\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_br,#area_ca,#area_mx,#area_de,#area_fr,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_ca\").click(function(){ $(\"#flag_ca\").addClass(\"area_show\"); $(\"#flag_us,#flag_br,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_ca\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_br,#area_mx,#area_de,#area_fr,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_mx\").click(function(){ $(\"#flag_mx\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_br,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_mx\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_br,#area_de,#area_fr,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_de\").click(function(){ $(\"#flag_de\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_br,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_de\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_br,#area_fr,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_fr\").click(function(){ $(\"#flag_fr\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_br,#flag_sg,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_fr\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_br,#area_sg,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_sg\").click(function(){ $(\"#flag_sg\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_br,#flag_jp,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_sg\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_fr,#area_br,#area_jp,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_jp\").click(function(){ $(\"#flag_jp\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_br,#flag_au,#flag_gb\").removeClass(\"area_show\"); $(\"#area_jp\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_fr,#area_sg,#area_br,#area_au,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_au\").click(function(){ $(\"#flag_au\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_br,#flag_gb\").removeClass(\"area_show\"); $(\"#area_au\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_fr,#area_sg,#area_jp,#area_br,#area_gb\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\"#flag_gb\").click(function(){ $(\"#flag_gb\").addClass(\"area_show\"); $(\"#flag_us,#flag_ca,#flag_mx,#flag_de,#flag_fr,#flag_sg,#flag_jp,#flag_au,#flag_br\").removeClass(\"area_show\"); $(\"#area_gb\").addClass(\"div_show\").removeClass(\"div_hidden\"); $(\"#area_us,#area_ca,#area_mx,#area_de,#area_fr,#area_sg,#area_jp,#area_au,#area_br\").addClass(\"div_hidden\").removeClass(\"div_show\"); }); $(\".select_item\").click(function(d){ d.preventDefault(); var p = $(this).data(\"port\"); $(\"#port_id\").val(p); var n = $(this).data(\"name\"); $(\"#port_name\").val(n); document.getElementById(\"mm-action-play\").click(); }); <\/script><p id=\"epx_time\" style=\"text-align: center;position: absolute;bottom: -15px;width: 100%;background-image: linear-gradient(#22ffcd, #cb5dc5); font-weight: bold; color: white; border: 1px solid;border-radius: 10px;border-color: #ffffff;\">Tiktok 👑 Kinq Team (YILDO)<\/p><p id=\"update_new_2\" style=\"text-align: center;position: absolute;bottom: -15px;width: 100%;background-image: linear-gradient(#ffffff, #ffffff);font-weight: bold;color: black;border: 1px solid;border-radius: 10px;border-color: #ffffff;\">\u0645\u0646 \u0641\u0636\u0644\u0643 \u060c \u0627\u0645\u0633\u062d \u0633\u062c\u0644 \u0627\u0644\u0645\u062a\u0635\u0641\u062d \u0644\u062a\u062d\u062f\u064a\u062b \u0627\u0644\u0627\u0645\u062a\u062f\u0627\u062f. \u0634\u0643\u0631\u064b\u0627.<\/p>",
    "propertyList": [{
        "id": 386,
        "type": "SKIN"
    }, {
        "id": 387,
        "type": "SKIN"
    }, {
        "id": 388,
        "type": "SKIN"
    }, {
        "id": 394,
        "type": "SKIN"
    }, {
        "id": 400,
        "type": "SKIN"
    }, {
        "id": 401,
        "type": "SKIN"
    }, {
        "id": 402,
        "type": "SKIN"
    }, {
        "id": 403,
        "type": "SKIN"
    }, {
        "id": 404,
        "type": "SKIN"
    }, {
        "id": 405,
        "type": "SKIN"
    }, {
        "id": 406,
        "type": "SKIN"
    }, {
        "id": 407,
        "type": "SKIN"
    }, {
        "id": 408,
        "type": "SKIN"
    }, {
        "id": 409,
        "type": "SKIN"
    }, {
        "id": 410,
        "type": "SKIN"
    }, {
        "id": 411,
        "type": "SKIN"
    }, {
        "id": 412,
        "type": "SKIN"
    }, {
        "id": 413,
        "type": "SKIN"
    }, {
        "id": 414,
        "type": "SKIN"
    }, {
        "id": 415,
        "type": "SKIN"
    }, {
        "id": 416,
        "type": "SKIN"
    }, {
        "id": 417,
        "type": "SKIN"
    }, {
        "id": 418,
        "type": "SKIN"
    }, {
        "id": 419,
        "type": "SKIN"
    }, {
        "id": 420,
        "type": "SKIN"
    }, {
        "id": 421,
        "type": "SKIN"
    }, {
        "id": 422,
        "type": "SKIN"
    }, {
        "id": 423,
        "type": "SKIN"
    }, {
        "id": 424,
        "type": "SKIN"
    }, {
        "id": 425,
        "type": "SKIN"
    }, {
        "id": 426,
        "type": "SKIN"
    }, {
        "id": 427,
        "type": "SKIN"
    }, {
        "id": 428,
        "type": "SKIN"
    }, {
        "id": 429,
        "type": "SKIN"
    }, {
        "id": 430,
        "type": "SKIN"
    }, {
        "id": 431,
        "type": "SKIN"
    }, {
        "id": 432,
        "type": "SKIN"
    }, {
        "id": 433,
        "type": "SKIN"
    }, {
        "id": 434,
        "type": "SKIN"
    }, {
        "id": 435,
        "type": "SKIN"
    }, {
        "id": 436,
        "type": "SKIN"
    }, {
        "id": 437,
        "type": "SKIN"
    }, {
        "id": 438,
        "type": "SKIN"
    }, {
        "id": 439,
        "type": "SKIN"
    }, {
        "id": 440,
        "type": "SKIN"
    }, {
        "id": 441,
        "type": "SKIN"
    }, {
        "id": 442,
        "type": "SKIN"
    }, {
        "id": 443,
        "type": "SKIN"
    }, {
        "id": 444,
        "type": "SKIN"
    }, {
        "id": 445,
        "type": "SKIN"
    }, {
        "id": 446,
        "type": "SKIN"
    }, {
        "id": 447,
        "type": "SKIN"
    }, {
        "id": 448,
        "type": "SKIN"
    }, {
        "id": 449,
        "type": "SKIN"
    }, {
        "id": 450,
        "type": "SKIN"
    }, {
        "id": 451,
        "type": "SKIN"
    }, {
        "id": 452,
        "type": "SKIN"
    }, {
        "id": 453,
        "type": "SKIN"
    }, {
        "id": 454,
        "type": "SKIN"
    }, {
        "id": 455,
        "type": "SKIN"
    }, {
        "id": 456,
        "type": "SKIN"
    }, {
        "id": 457,
        "type": "SKIN"
    }, {
        "id": 458,
        "type": "SKIN"
    }, {
        "id": 459,
        "type": "SKIN"
    }, {
        "id": 460,
        "type": "SKIN"
    }, {
        "id": 461,
        "type": "SKIN"
    }, {
        "id": 462,
        "type": "SKIN"
    }, {
        "id": 463,
        "type": "SKIN"
    }, {
        "id": 464,
        "type": "SKIN"
    }, {
        "id": 465,
        "type": "SKIN"
    }, {
        "id": 466,
        "type": "SKIN"
    }, {
        "id": 467,
        "type": "SKIN"
    }, {
        "id": 468,
        "type": "SKIN"
    }, {
        "id": 471,
        "type": "SKIN"
    }, {
        "id": 472,
        "type": "SKIN"
    }, {
        "id": 473,
        "type": "SKIN"
    }, {
        "id": 474,
        "type": "SKIN"
    }, {
        "id": 475,
        "type": "SKIN"
    }, {
        "id": 476,
        "type": "SKIN"
    }, {
        "id": 477,
        "type": "SKIN"
    }, {
        "id": 478,
        "type": "SKIN"
    }, {
        "id": 479,
        "type": "SKIN"
    }, {
        "id": 480,
        "type": "SKIN"
    }, {
        "id": 481,
        "type": "SKIN"
    }, {
        "id": 482,
        "type": "SKIN"
    }, {
        "id": 483,
        "type": "SKIN"
    }, {
        "id": 484,
        "type": "SKIN"
    }, {
        "id": 485,
        "type": "SKIN"
    }, {
        "id": 486,
        "type": "SKIN"
    }, {
        "id": 487,
        "type": "SKIN"
    }, {
        "id": 488,
        "type": "SKIN"
    }, {
        "id": 489,
        "type": "SKIN"
    }, {
        "id": 490,
        "type": "SKIN"
    }, {
        "id": 523,
        "type": "SKIN"
    }, {
        "id": 555,
        "type": "SKIN"
    }, {
        "id": 550,
        "type": "SKIN"
    }, {
        "id": 551,
        "type": "SKIN"
    }, {
        "id": 552,
        "type": "SKIN"
    }, {
        "id": 553,
        "type": "SKIN"
    }, {
        "id": 554,
        "type": "SKIN"
    }, {
        "id": 556,
        "type": "SKIN"
    }, {
        "id": 557,
        "type": "SKIN"
    }, {
        "id": 558,
        "type": "SKIN"
    }, {
        "id": 560,
        "type": "SKIN"
    }, {
        "id": 561,
        "type": "SKIN"
    }, {
        "id": 562,
        "type": "SKIN"
    }, {
        "id": 563,
        "type": "SKIN"
    }, {
        "id": 564,
        "type": "SKIN"
    }, {
        "id": 565,
        "type": "SKIN"
    }, {
        "id": 567,
        "type": "SKIN"
    }, {
        "id": 568,
        "type": "SKIN"
    }, {
        "id": 569,
        "type": "SKIN"
    }, {
        "id": 570,
        "type": "SKIN"
    }, {
        "id": 571,
        "type": "SKIN"
    }, {
        "id": 573,
        "type": "SKIN"
    }, {
        "id": 574,
        "type": "SKIN"
    }, {
        "id": 575,
        "type": "SKIN"
    }, {
        "id": 576,
        "type": "SKIN"
    }, {
        "id": 577,
        "type": "SKIN"
    }, {
        "id": 578,
        "type": "SKIN"
    }, {
        "id": 579,
        "type": "SKIN"
    }, {
        "id": 580,
        "type": "SKIN"
    }, {
        "id": 585,
        "type": "SKIN"
    }, {
        "id": 586,
        "type": "SKIN"
    }, {
        "id": 590,
        "type": "SKIN"
    }, {
        "id": 599,
        "type": "SKIN"
    }, {
        "id": 600,
        "type": "SKIN"
    }, {
        "id": 601,
        "type": "SKIN"
    }, {
        "id": 610,
        "type": "SKIN"
    }, {
        "id": 611,
        "type": "SKIN"
    }, {
        "id": 615,
        "type": "SKIN"
    }, {
        "id": 617,
        "type": "SKIN"
    }, {
        "id": 629,
        "type": "SKIN"
    }, {
        "id": 631,
        "type": "SKIN"
    }, {
        "id": 648,
        "type": "SKIN"
    }, {
        "id": 649,
        "type": "SKIN"
    }, {
        "id": 635,
        "type": "SKIN"
    }, {
        "id": 646,
        "type": "SKIN"
    }, {
        "id": 647,
        "type": "SKIN"
    }, {
        "id": 657,
        "type": "SKIN"
    }, {
        "id": 658,
        "type": "SKIN"
    }, {
        "id": 666,
        "type": "SKIN"
    }, {
        "id": 684,
        "type": "SKIN"
    }, {
        "id": 685,
        "type": "SKIN"
    }, {
        "id": 686,
        "type": "SKIN"
    }, {
        "id": 687,
        "type": "SKIN"
    }, {
        "id": 688,
        "type": "SKIN"
    }, {
        "id": 730,
        "type": "SKIN"
    }, {
        "id": 731,
        "type": "SKIN"
    }, {
        "id": 732,
        "type": "SKIN"
    }, {
        "id": 733,
        "type": "SKIN"
    }, {
        "id": 734,
        "type": "SKIN"
    }, {
        "id": 770,
        "type": "SKIN"
    }, {
        "id": 771,
        "type": "SKIN"
    }, {
        "id": 772,
        "type": "SKIN"
    }, {
        "id": 773,
        "type": "SKIN"
    }, {
        "id": 774,
        "type": "SKIN"
    }, {
        "id": 775,
        "type": "SKIN"
    }, {
        "id": 776,
        "type": "SKIN"
    }, {
        "id": 777,
        "type": "SKIN"
    }, {
        "id": 778,
        "type": "SKIN"
    }, {
        "id": 779,
        "type": "SKIN"
    }, {
        "id": 780,
        "type": "SKIN"
    }, {
        "id": 781,
        "type": "SKIN"
    }, {
        "id": 782,
        "type": "SKIN"
    }, {
        "id": 783,
        "type": "SKIN"
    }, {
        "id": 784,
        "type": "SKIN"
    }, {
        "id": 785,
        "type": "SKIN"
    }, {
        "id": 786,
        "type": "SKIN"
    }, {
        "id": 798,
        "type": "SKIN"
    }, {
        "id": 799,
        "type": "SKIN"
    }, {
        "id": 750,
        "type": "SKIN"
    }, {
        "id": 759,
        "type": "SKIN"
    }, {
        "id": 751,
        "type": "SKIN"
    }, {
        "id": 754,
        "type": "SKIN"
    }, {
        "id": 369,
        "type": "SKIN"
    }, {
        "id": 397,
        "type": "SKIN"
    }, {
        "id": 528,
        "type": "SKIN"
    }, {
        "id": 529,
        "type": "SKIN"
    }, {
        "id": 534,
        "type": "SKIN"
    }, {
        "id": 543,
        "type": "SKIN"
    }, {
        "id": 603,
        "type": "SKIN"
    }, {
        "id": 604,
        "type": "SKIN"
    }, {
        "id": 800,
        "type": "SKIN"
    }, {
        "id": 801,
        "type": "SKIN"
    }, {
        "id": 802,
        "type": "SKIN"
    }, {
        "id": 807,
        "type": "SKIN"
    }, {
        "id": 808,
        "type": "SKIN"
    }, {
        "id": 809,
        "type": "SKIN"
    }, {
        "id": 744,
        "type": "SKIN"
    }, {
        "id": 496,
        "type": "SKIN"
    }, {
        "id": 400,
        "type": "EYES"
    }, {
        "id": 401,
        "type": "EYES"
    }, {
        "id": 402,
        "type": "EYES"
    }, {
        "id": 403,
        "type": "EYES"
    }, {
        "id": 404,
        "type": "EYES"
    }, {
        "id": 405,
        "type": "EYES"
    }, {
        "id": 406,
        "type": "EYES"
    }, {
        "id": 407,
        "type": "EYES"
    }, {
        "id": 408,
        "type": "EYES"
    }, {
        "id": 409,
        "type": "EYES"
    }, {
        "id": 410,
        "type": "EYES"
    }, {
        "id": 411,
        "type": "EYES"
    }, {
        "id": 412,
        "type": "EYES"
    }, {
        "id": 413,
        "type": "EYES"
    }, {
        "id": 414,
        "type": "EYES"
    }, {
        "id": 415,
        "type": "EYES"
    }, {
        "id": 416,
        "type": "EYES"
    }, {
        "id": 417,
        "type": "EYES"
    }, {
        "id": 418,
        "type": "EYES"
    }, {
        "id": 419,
        "type": "EYES"
    }, {
        "id": 420,
        "type": "EYES"
    }, {
        "id": 421,
        "type": "EYES"
    }, {
        "id": 422,
        "type": "EYES"
    }, {
        "id": 423,
        "type": "EYES"
    }, {
        "id": 424,
        "type": "EYES"
    }, {
        "id": 425,
        "type": "EYES"
    }, {
        "id": 426,
        "type": "EYES"
    }, {
        "id": 427,
        "type": "EYES"
    }, {
        "id": 428,
        "type": "EYES"
    }, {
        "id": 429,
        "type": "EYES"
    }, {
        "id": 430,
        "type": "EYES"
    }, {
        "id": 431,
        "type": "EYES"
    }, {
        "id": 432,
        "type": "EYES"
    }, {
        "id": 433,
        "type": "EYES"
    }, {
        "id": 434,
        "type": "EYES"
    }, {
        "id": 731,
        "type": "EYES"
    }, {
        "id": 732,
        "type": "EYES"
    }, {
        "id": 733,
        "type": "EYES"
    }, {
        "id": 734,
        "type": "EYES"
    }, {
        "id": 735,
        "type": "EYES"
    }, {
        "id": 736,
        "type": "EYES"
    }, {
        "id": 737,
        "type": "EYES"
    }, {
        "id": 738,
        "type": "EYES"
    }, {
        "id": 739,
        "type": "EYES"
    }, {
        "id": 740,
        "type": "EYES"
    }, {
        "id": 741,
        "type": "EYES"
    }, {
        "id": 742,
        "type": "EYES"
    }, {
        "id": 402,
        "type": "GLASSES"
    }, {
        "id": 403,
        "type": "GLASSES"
    }, {
        "id": 404,
        "type": "GLASSES"
    }, {
        "id": 405,
        "type": "GLASSES"
    }, {
        "id": 406,
        "type": "GLASSES"
    }, {
        "id": 407,
        "type": "GLASSES"
    }, {
        "id": 412,
        "type": "GLASSES"
    }, {
        "id": 413,
        "type": "GLASSES"
    }, {
        "id": 414,
        "type": "GLASSES"
    }, {
        "id": 415,
        "type": "GLASSES"
    }, {
        "id": 416,
        "type": "GLASSES"
    }, {
        "id": 417,
        "type": "GLASSES"
    }, {
        "id": 418,
        "type": "GLASSES"
    }, {
        "id": 419,
        "type": "GLASSES"
    }, {
        "id": 420,
        "type": "GLASSES"
    }, {
        "id": 421,
        "type": "GLASSES"
    }, {
        "id": 401,
        "type": "GLASSES"
    }, {
        "id": 423,
        "type": "GLASSES"
    }, {
        "id": 424,
        "type": "GLASSES"
    }, {
        "id": 400,
        "type": "HAT"
    }, {
        "id": 402,
        "type": "HAT"
    }, {
        "id": 403,
        "type": "HAT"
    }, {
        "id": 404,
        "type": "HAT"
    }, {
        "id": 406,
        "type": "HAT"
    }, {
        "id": 407,
        "type": "HAT"
    }, {
        "id": 408,
        "type": "HAT"
    }, {
        "id": 409,
        "type": "HAT"
    }, {
        "id": 410,
        "type": "HAT"
    }, {
        "id": 411,
        "type": "HAT"
    }, {
        "id": 412,
        "type": "HAT"
    }, {
        "id": 413,
        "type": "HAT"
    }, {
        "id": 414,
        "type": "HAT"
    }, {
        "id": 415,
        "type": "HAT"
    }, {
        "id": 416,
        "type": "HAT"
    }, {
        "id": 417,
        "type": "HAT"
    }, {
        "id": 418,
        "type": "HAT"
    }, {
        "id": 419,
        "type": "HAT"
    }, {
        "id": 420,
        "type": "HAT"
    }, {
        "id": 421,
        "type": "HAT"
    }, {
        "id": 422,
        "type": "HAT"
    }, {
        "id": 423,
        "type": "HAT"
    }, {
        "id": 424,
        "type": "HAT"
    }, {
        "id": 425,
        "type": "HAT"
    }, {
        "id": 429,
        "type": "HAT"
    }, {
        "id": 430,
        "type": "HAT"
    }, {
        "id": 431,
        "type": "HAT"
    }, {
        "id": 432,
        "type": "HAT"
    }, {
        "id": 436,
        "type": "HAT"
    }, {
        "id": 437,
        "type": "HAT"
    }, {
        "id": 438,
        "type": "HAT"
    }, {
        "id": 442,
        "type": "HAT"
    }, {
        "id": 443,
        "type": "HAT"
    }, {
        "id": 444,
        "type": "HAT"
    }, {
        "id": 445,
        "type": "HAT"
    }, {
        "id": 447,
        "type": "HAT"
    }, {
        "id": 448,
        "type": "HAT"
    }, {
        "id": 451,
        "type": "HAT"
    }, {
        "id": 452,
        "type": "HAT"
    }, {
        "id": 453,
        "type": "HAT"
    }, {
        "id": 455,
        "type": "HAT"
    }, {
        "id": 463,
        "type": "HAT"
    }, {
        "id": 465,
        "type": "HAT"
    }, {
        "id": 467,
        "type": "HAT"
    }, {
        "id": 426,
        "type": "HAT"
    }, {
        "id": 427,
        "type": "HAT"
    }, {
        "id": 441,
        "type": "HAT"
    }, {
        "id": 446,
        "type": "HAT"
    }, {
        "id": 462,
        "type": "HAT"
    }, {
        "id": 739,
        "type": "HAT"
    }, {
        "id": 740,
        "type": "HAT"
    }, {
        "id": 741,
        "type": "HAT"
    }, {
        "id": 742,
        "type": "HAT"
    }, {
        "id": 743,
        "type": "HAT"
    }, {
        "id": 744,
        "type": "HAT"
    }, {
        "id": 745,
        "type": "HAT"
    }, {
        "id": 747,
        "type": "HAT"
    }, {
        "id": 748,
        "type": "HAT"
    }, {
        "id": 749,
        "type": "HAT"
    }, {
        "id": 750,
        "type": "HAT"
    }, {
        "id": 753,
        "type": "HAT"
    }, {
        "id": 754,
        "type": "HAT"
    }, {
        "id": 755,
        "type": "HAT"
    }, {
        "id": 756,
        "type": "HAT"
    }, {
        "id": 757,
        "type": "HAT"
    }, {
        "id": 767,
        "type": "HAT"
    }, {
        "id": 768,
        "type": "HAT"
    }, {
        "id": 774,
        "type": "HAT"
    }, {
        "id": 775,
        "type": "HAT"
    }, {
        "id": 776,
        "type": "HAT"
    }, {
        "id": 777,
        "type": "HAT"
    }, {
        "id": 778,
        "type": "HAT"
    }, {
        "id": 779,
        "type": "HAT"
    }, {
        "id": 780,
        "type": "HAT"
    }, {
        "id": 781,
        "type": "HAT"
    }, {
        "id": 782,
        "type": "HAT"
    }, {
        "id": 783,
        "type": "HAT"
    }, {
        "id": 784,
        "type": "HAT"
    }, {
        "id": 785,
        "type": "HAT"
    }, {
        "id": 405,
        "type": "HAT"
    }, {
        "id": 433,
        "type": "HAT"
    }, {
        "id": 434,
        "type": "HAT"
    }, {
        "id": 439,
        "type": "HAT"
    }, {
        "id": 459,
        "type": "HAT"
    }, {
        "id": 460,
        "type": "HAT"
    }, {
        "id": 464,
        "type": "HAT"
    }, {
        "id": 400,
        "type": "MOUTH"
    }, {
        "id": 401,
        "type": "MOUTH"
    }, {
        "id": 402,
        "type": "MOUTH"
    }, {
        "id": 403,
        "type": "MOUTH"
    }, {
        "id": 404,
        "type": "MOUTH"
    }, {
        "id": 405,
        "type": "MOUTH"
    }, {
        "id": 406,
        "type": "MOUTH"
    }, {
        "id": 500,
        "type": "SKIN"
    }, {
        "id": 502,
        "type": "SKIN"
    }, {
        "id": 504,
        "type": "SKIN"
    }, {
        "id": 505,
        "type": "SKIN"
    }, {
        "id": 506,
        "type": "SKIN"
    }, {
        "id": 507,
        "type": "SKIN"
    }, {
        "id": 516,
        "type": "SKIN"
    }, {
        "id": 517,
        "type": "SKIN"
    }, {
        "id": 526,
        "type": "SKIN"
    }, {
        "id": 533,
        "type": "SKIN"
    }, {
        "id": 537,
        "type": "SKIN"
    }, {
        "id": 540,
        "type": "SKIN"
    }, {
        "id": 546,
        "type": "SKIN"
    }, {
        "id": 2200,
        "type": "SKIN"
    }, {
        "id": 699,
        "type": "SKIN"
    }, {
        "id": 382,
        "type": "SKIN"
    }, {
        "id": 375,
        "type": "SKIN"
    }, {
        "id": 522,
        "type": "SKIN"
    }, {
        "id": 530,
        "type": "SKIN"
    }, {
        "id": 542,
        "type": "SKIN"
    }, {
        "id": 370,
        "type": "SKIN"
    }, {
        "id": 527,
        "type": "SKIN"
    }, {
        "id": 746,
        "type": "SKIN"
    }, {
        "id": 491,
        "type": "SKIN"
    }, {
        "id": 492,
        "type": "SKIN"
    }, {
        "id": 753,
        "type": "SKIN"
    }, {
        "id": 458,
        "type": "HAT"
    }, {
        "id": 449,
        "type": "HAT"
    }, {
        "id": 450,
        "type": "HAT"
    }, {
        "id": 454,
        "type": "HAT"
    }, {
        "id": 456,
        "type": "HAT"
    }, {
        "id": 457,
        "type": "HAT"
    }, {
        "id": 461,
        "type": "HAT"
    }, {
        "id": 743,
        "type": "EYES"
    }, {
        "id": 744,
        "type": "EYES"
    }, {
        "id": 409,
        "type": "GLASSES"
    }, {
        "id": 410,
        "type": "GLASSES"
    }, {
        "id": 411,
        "type": "GLASSES"
    }, {
        "id": 425,
        "type": "GLASSES"
    }, {
        "id": 427,
        "type": "GLASSES"
    }, {
        "id": 428,
        "type": "GLASSES"
    }, {
        "id": 429,
        "type": "GLASSES"
    }, {
        "id": 430,
        "type": "GLASSES"
    }, {
        "id": 431,
        "type": "GLASSES"
    }, {
        "id": 494,
        "type": "SKIN"
    }, {
        "id": 769,
        "type": "HAT"
    }, {
        "id": 793,
        "type": "HAT"
    }, {
        "id": 794,
        "type": "HAT"
    }, {
        "id": 798,
        "type": "HAT"
    }, {
        "id": 795,
        "type": "HAT"
    }, {
        "id": 797,
        "type": "HAT"
    }, {
        "id": 468,
        "type": "HAT"
    }, {
        "id": 731,
        "type": "HAT"
    }, {
        "id": 732,
        "type": "HAT"
    }, {
        "id": 401,
        "type": "HAT"
    }, {
        "id": 759,
        "type": "HAT"
    }, {
        "id": 800,
        "type": "HAT"
    }, {
        "id": 735,
        "type": "HAT"
    }, {
        "id": 737,
        "type": "HAT"
    }, {
        "id": 738,
        "type": "HAT"
    }, {
        "id": 440,
        "type": "HAT"
    }, {
        "id": 734,
        "type": "HAT"
    }, {
        "id": 799,
        "type": "HAT"
    }, {
        "id": 751,
        "type": "HAT"
    }, {
        "id": 796,
        "type": "HAT"
    }, {
        "id": 758,
        "type": "HAT"
    }, {
        "id": 698,
        "type": "SKIN"
    }, {
        "id": 713,
        "type": "SKIN"
    }, {
        "id": 660,
        "type": "SKIN"
    }, {
        "id": 620,
        "type": "SKIN"
    }, {
        "id": 714,
        "type": "SKIN"
    }, {
        "id": 722,
        "type": "SKIN"
    }, {
        "id": 719,
        "type": "SKIN"
    }, {
        "id": 692,
        "type": "SKIN"
    }, {
        "id": 761,
        "type": "SKIN"
    }, {
        "id": 693,
        "type": "SKIN"
    }, {
        "id": 662,
        "type": "SKIN"
    }, {
        "id": 643,
        "type": "SKIN"
    }, {
        "id": 596,
        "type": "SKIN"
    }, {
        "id": 740,
        "type": "SKIN"
    }, {
        "id": 724,
        "type": "SKIN"
    }, {
        "id": 742,
        "type": "SKIN"
    }, {
        "id": 515,
        "type": "SKIN"
    }, {
        "id": 642,
        "type": "SKIN"
    }, {
        "id": 634,
        "type": "SKIN"
    }],
    "mb": "<h4 class=\"center\">\u0623\u0632\u0631\u0627\u0631 \u0627\u0644\u062a\u062d\u0643\u0645 \u0641\u064a \u0647\u0627\u062a\u0641 Android<\/h4><table><tr><td><label for=\"joystick_checked\">\u062a\u0634\u063a\u064a\u0644 \u0623\u0648 \u0625\u064a\u0642\u0627\u0641<\/label> <input type=\"checkbox\" id=\"joystick_checked\" value=\"true\" checked><\/td><td> <label for=\"joystick_color\">\u0627\u0644\u0644\u0648\u0646<\/label> <select id=\"joystick_color\"> <option value=\"red\">\u0623\u062d\u0645\u0631<\/option> <option value=\"blue\">\u0623\u0632\u0631\u0642<\/option> <option value=\"black\">\u0623\u0633\u0648\u062f<\/option> <option value=\"white\">\u0623\u0628\u064a\u0636<\/option> <\/select><\/td><\/tr><tr><td> <label for=\"joystick_mode\">\u0623\u0633\u0627\u0644\u064a\u0628<\/label> <select id=\"joystick_mode\"> <option value=\"dynamic\">\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u064a\u0646\u0627\u0645\u064a\u0643\u064a<\/option> <option value=\"static\">\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062b\u0627\u0628\u062a<\/option> <\/select><\/td><td> <label for=\"joystick_position\">\u062d\u0627\u0641\u0629<\/label> <select id=\"joystick_position\"> <option value=\"L\">\u0627\u0644\u064a\u0633\u0627\u0631<\/option> <option value=\"R\">\u062d\u0642<\/option> <\/select><\/td><\/tr><tr><td> <label for=\"joystick_size\">\u0628\u062d\u062c\u0645<\/label> <select id=\"joystick_size\"> <option value=\"90\">90<\/option> <option value=\"100\">100<\/option> <option value=\"110\">110<\/option> <\/select><\/td><td> <label for=\"joystick_pxy\">\u0625\u062d\u062f\u0627\u062b\u064a\u0627\u062a(X,Y)<\/label> <select id=\"joystick_pxy\"> <option value=\"90\">(90,90)<\/option> <option value=\"100\">(100,100)<\/option> <option value=\"110\">(110,110)<\/option> <\/select><\/td><\/tr><\/table>",
    "cm": "",
    "cr": "<img src=\"https:\/\/wormx.store\/2025\/check\/test.png\" style=\"margin: 1px 0;\">",
    "ccc": "iq",
    "ccg": ["\u0633\u062a\u062a\u0645 \u0625\u0632\u0627\u0644\u0629 \u0625\u062d\u0635\u0627\u0626\u064a\u0627\u062a Kill and Headshot\u061f", "\u0643\u0627\u0646\u062a \u0647\u0646\u0627\u0643 \u0645\u0634\u0643\u0644\u0629 \u0641\u064a \u0627\u0644\u0627\u062a\u0635\u0627\u0644!", "\u062a\u0645 \u0642\u0641\u0644 \u062d\u0633\u0627\u0628\u0643.", "\u0627\u0639\u0627\u062f\u062a\u0647\u0627", "\u0643\u0627\u0645\u0644 \u0627\u0644\u0634\u0627\u0634\u0629", "\u0641\u064a \u0627\u0644\u0645\u0628\u0627\u0631\u0627\u0629", "\u2699\ufe0f", "\u0645\u0639\u0631\u0641 \u0627\u0644\u062d\u0633\u0627\u0628", "\u0646\u0633\u062e \u0645\u0639\u0631\u0641 \u0627\u0644\u062d\u0633\u0627\u0628", "\u0646\u0633\u062e \u0627\u0644\u0647\u0648\u064a\u0629", "\u0627\u0644\u0623\u0645\u0629", "\u062a\u0630\u0643\u0631 \u0639\u062f\u062f \u062d\u0627\u0644\u0627\u062a \u0627\u0644\u0642\u062a\u0644 \u0648\u0625\u0635\u0627\u0628\u0629 \u0627\u0644\u0631\u0623\u0633", "\u062a\u0634\u063a\u064a\u0644 \u0623\u0648 \u0625\u064a\u0642\u0627\u0641", "\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u062e\u0644\u0641\u064a\u0629", "\u0646\u0633\u062e", "\u0641\u064a\u062a\u0646\u0627\u0645", "\u062a\u0627\u064a\u0644\u0627\u0646\u062f", "\u0643\u0645\u0628\u0648\u062f\u064a\u0627", "\u0625\u0646\u062f\u0648\u0646\u064a\u0633\u064a\u0627", "\u0633\u0646\u063a\u0627\u0641\u0648\u0631\u0629", "\u0627\u0644\u064a\u0627\u0628\u0627\u0646", "\u0627\u0644\u0645\u0643\u0633\u064a\u0643", "\u0627\u0644\u0628\u0631\u0627\u0632\u064a\u0644", "\u0643\u0646\u062f\u0627", "\u0623\u0644\u0645\u0627\u0646\u064a\u0627", "\u0641\u0631\u0646\u0633\u0627", "\u0625\u0646\u0643\u0644\u062a\u0631\u0627", "\u0623\u0633\u062a\u0631\u0627\u0644\u064a\u0627", "USA", "\u0627\u0644\u0628\u0631\u062a\u063a\u0627\u0644", "\u062a\u0642\u0635\u064a\u0631", "\u0633\u0645\u0627\u0621 \u0632\u0631\u0642\u0627\u0621 \u062f\u0627\u0643\u0646\u0629", "\u0627\u0644\u0633\u0645\u0627\u0621 \u0627\u0644\u0623\u0631\u062c\u0648\u0627\u0646\u064a", "\u0633\u062d\u0627\u0628", "\ud83d\udca1", "\u062f\u064a\u0643 \u0631\u0648\u0645\u0649", "\u0639\u0631\u0628"],
    "streamer": "CindyNana GM",
    "programmer": "Pham Phu Bach",
    "extension": "TimmapWormate",
    "game": "Wormate.io",
    "note": "Please don't copy my code",
    "z": "c",
    "s11": "2053260921032064270820262285128020172095105009562567188614030501219626250201098822492262210320642708202622851280201720951050095625671886140305012196.0.20532609210320642708202622851280201720951050095625671886140305012196262502010988.260920642053221226092103114201651311151603320407236814042465.2111274602130296053612792091004222142403016201351764017118200327106503710702072507860809108410911163258412301533175017701908240510262703265010001555.109108090560175027030135039203710327088507021084116312301216190819752405258426501026017117502476.270319752650.20532609210320642708202622851280201720951050095625671886.0171177007862499.2053260921032064.2238016503320407260921031142206413111516205322122368140426091216",
    "sw": 1,
    "tt": 0,
    "vs": 170,
    "dsg": ["100|491", "104|492", "133|494", "1146|717", "687|757", "1002|703"]
}